language: node_js
node_js:
  - node
sudo: false
branches:
  except:
    - gh-pages
before_script:
  - npm install -g bower
  - bower install
script:
  - npm run lint
  - npm run build
after_success:
  - ./deploy.sh
